### ISSUE TITLE
Images don't respect exif orientation when resized

### ISSUE THREAD

**Issue by leafo** [leafo/streak.club#16]

**Comment by egonSchiele** [comment]
+1. I noticed a few ways to do this:

- you can pass in the `-auto-orient` option when resizing: http://stackoverflow.com/a/24896610/139117
-  it looks like the magick package has support for getting orientation info for images
- You can also read the info from the imagemagick cmd line tool ... `identify -verbose <image>` gives `Orientation: BottomRight`.

I can submit a PR for this if you know of a good way to do it

**Comment by leafo** [comment]
we already have a `auto_orient` method in [magick](https://github.com/leafo/magick/blob/master/magick/wand/image.moon)

It needs to be called when image thumbnails are made in https://github.com/leafo/streak.club/blob/master/applications/images.moon#L77
