### ISSUE TITLE
Email is taken: Forgot Username/Password?.

### ISSUE THREAD

**Issue by VividReality** [leafo/streak.club#20]
I am trying to register, but:

Email adress is taken, even though I don't recall registering.

Usually I'd do "forgot password" or "forgot username", but there is no way I could find out for doing so, would there be a way to add this? Lets say I tell the website I forgot my username and password for someone@somewhere.com, it'd send a mail to that email adress with something in the lines of "dear [user name], it seems you forgot your password, please follow these steps...".

Since there was no way of finding anything like this, I tried the following:

I tried looking in my webmail, there is no mail from the website.

I tried logging in with one of my usual passwords, none exist on your website.

**Comment by leafo** [comment]
sorry,

can you tell me your email address and I'll send you a temporary password until I have password reset coded!

**Comment by VividReality** [comment]
Thanks! I am looking forward until this feature is available.
