### ISSUE TITLE
How can I set up my own streak.club?

### ISSUE THREAD

**Issue by DragonStuff** [leafo/streak.club#26]
Could a quick update to README.MD be made referring to the options in the Makefile and how to set it up?
I've got Lapis, OpenResty etc all set up, but I'm hitting problems with bcrypt and I spent at least an hour trying to figure out dependencies etc. Still don't quite know how this should be set up though.

Thanks!

**Comment by leafo** [comment]
Sorry there are no directions yet, you can try the ones for this project, the stack is effectively the same: 

https://github.com/leafo/luarocks-site#how-to-run-locally

**Comment by qaisjp** [comment]
If bcrypt is being arsey, don't forget to look for processor arch differences

**Comment by DragonStuff** [comment]
Thanks guys! I'll get started trying to get this working :smiley: 

Thanks,
DragonStuff.

**Comment by DragonStuff** [comment]
Unfortunately after working though everything and starting up the Lapis server, I get:

```
2015/04/22 03:24:03 [error] 20508#0: *1 lua entry thread aborted: runtime error: /usr/local/share/lua/5.1/lapis/init.lua:15: module 'app' not found:
        no field package.preload['app']
        no file '/usr/local/openresty/lualib/app.lua'
        no file '/usr/local/openresty/lualib/app/init.lua'
        no file './app.lua'
        no file '/usr/local/openresty/luajit/share/luajit-2.1.0-alpha/app.lua'
        no file '/usr/local/share/lua/5.1/app.lua'
        no file '/usr/local/share/lua/5.1/app/init.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/app.lua'
        no file '/usr/local/openresty/luajit/share/lua/5.1/app/init.lua'
        no file '/usr/local/openresty/lualib/app.so'
        no file './app.so'
        no file '/usr/local/lib/lua/5.1/app.so'
        no file '/usr/local/openresty/luajit/lib/lua/5.1/app.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
coroutine 0:
        [C]: in function 'require'
        /usr/local/share/lua/5.1/lapis/init.lua:15: in function 'serve'
        content_by_lua(nginx.conf.compiled:32):2: in function <content_by_lua(nginx.conf.compiled:32):1>, client: 121.44.45.35, server: , request: "GET / HTTP/1.1", host: "ommitted"

```

**Comment by DragonStuff** [comment]
Solved, lapis seems to require that the directory ABOVE your project needs to be owned by the user it is running under as well. (In this case, project directory is /root/streak.club/, so /root/ needs to be chown'd to the user as well)

This is an odd behavior, but not related to streak.club, closing off.

**Comment by leafo** [comment]
This is lapis or nginx?

**Comment by DragonStuff** [comment]
I haven't had this issue with Nginx before, but I lack the knowledge of lapis to be able to determine where the issue is.
