### ISSUE TITLE
Please provide a true basic installation for streak.club setup.

### ISSUE THREAD

**Issue by hwongcom** [leafo/streak.club#27]
Please provide a true basic installation for streak.club setup... i'm learning moonscript and would like to see how to set up one.

Please help with how to set up from...
Clean Ubuntu server...
1. install openresty.
2. install luarocks?(is this necessary?) install moonscript? install lapis???
3. basic nginx configuration (download area, so can activate the nginx part)
4. set up the necessary db?
5. running it?

... sorry but totally clueless how to make it work.
if it can be like wordpress 5 min installation will be great.

**Comment by leafo** [comment]
You should be able to adapt this guide to apply it to streak club: https://github.com/leafo/luarocks-site#how-to-run-locally

The stacks are almost identical
