### ISSUE TITLE
don't know how to handle: boolean

### ISSUE THREAD

**Issue by heri** [leafo/streak.club#33]
Hello

I've got an error and don't know if it's related to streak or lapis. I'm from a Ruby background but quite intrigued by lapis. On a fresh install of streak.club, I run in the error : 
```
Error

/Users/heri/torch/install/share/lua/5.1/lapis/html.lua:350: don't know how to handle: boolean
Traceback

stack traceback:
	[C]: in function 'error'
	/Users/heri/torch/install/share/lua/5.1/lapis/html.lua:350: in function 'write'
	/Users/heri/torch/install/share/lua/5.1/lapis/html.lua:327: in function 'write_escaped'
	/Users/heri/torch/install/share/lua/5.1/lapis/html.lua:181: in function 'a'
	./views/layout.lua:167: in function 'call'
	/Users/heri/torch/install/share/lua/5.1/lapis/html.lua:348: in function 'write'
```

I haven't to been able to understand the source of error. On the Terminal:

```
2016/03/17 17:54:40 [notice] 28891#0: *12 [lua] postgres.lua:62: select(): SQL: SELECT * from "streaks" 
      where "publish_status" = 2 AND "category" = 1
      and           start_date > now() at time zone 'utc' + (hour_offset || ' hours')::interval
        
      order by users_count desc
     LIMIT 100 OFFSET 0, client: 127.0.0.1, server: , request: "GET /streaks/upcoming/visual-arts HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/streaks/upcoming/video"
2016/03/17 17:54:40 [notice] 28891#0: signal 20 (SIGCHLD) received
2016/03/17 17:54:40 [notice] 28891#0: unknown process 29067 exited with code 0
2016/03/17 17:54:40 [notice] 28891#0: *12 [lua] application.lua:478: handle_error(): [500] GET /streaks/upcoming/visual-arts - {}, client: 127.0.0.1, server: , request: "GET /streaks/upcoming/visual-arts HTTP/1.1", host: "localhost:8080", referrer: "http://localhost:8080/streaks/upcoming/video"
```

I have looked in the `lua/5.1/lapis/html.lua` file but I'm not sure of changing the source code of lapis and adding boolean case just to make an app work. 

Has anyone see this previously? Thank you.

**Comment by leafo** [comment]
These are the lines causing the error:

```
          revision = require "revision"
          a href: "https://github.com/leafo/streak.club/commit/#{revision}", rel: "nofollow", revision
```

What happens when you open a lua shell and print the return value of `require("revision")`?

**Comment by heri** [comment]
Hi
When I open a lua shell in the `streak.club` directory:
```
[heri]: lua
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> require("revision")
> 
```

But when I open a lua shell in another directory: 
```
> require("revision")
stdin:1: module 'revision' not found:
	no field package.preload['revision']
	no file '/Users/heri/.luarocks/share/lua/5.1/revision.lua'
	no file '/Users/heri/.luarocks/share/lua/5.1/revision/init.lua'
	no file '/Users/heri/torch/install/share/lua/5.1/revision.lua'
	no file '/Users/heri/torch/install/share/lua/5.1/revision/init.lua'
	no file './revision.lua'
...
```
I didn't find the module revision on luarocks. I was planning to study `streak.club` source code to learn lapis but I think I'm better off by starting with a simple basic app?

**Comment by leafo** [comment]
the module `revision` points to `revision.lua` in the streak.club directory. It's not a separate install.

As a quick test you can comment it out, and return an empty string, and see if the site loads for you

**Comment by heri** [comment]
Commented it out and recompiled to Lua. It works. Thanks @leafo

**Comment by leafo** [comment]
I can wrap that section in a pcall, it's not critical for the site to run

**Comment by heri** [comment]
Yes, that can be good. The error can discourage those who want to learn Lapis and try out `streak.club`. It's very hard to guess the problem comes from `require "revision"` by reading the error `don't know how to handle boolean`

**Comment by leafo** [comment]
I'm actually not entirely sure how that module returned a boolean value. You have git installed on your system?

What happens if you run this in the streak.club directory?

```
lua -e 'print(tostring(require("revision")))'
```

Lua should be Lua 5.1, or it can be LuaJIT, to match the environment that openresty is running in. (but it should work on any version since the module just runs a shell command)

**Comment by heri** [comment]
I have Lua 5.2 installed - So I have to downgrade to Lua 5.1 to use Lapis? 

Git is installed yes

The command outputs `f18b347`
