### ISSUE TITLE
Add ability to change email address and username

### ISSUE THREAD

**Issue by supergooddave** [leafo/streak.club#46]
I'd like to change both my email address and my username but I don't see a way to do this from the site. Maybe I'm missing something.

**Comment by leafo** [comment]
It was never coded, but I can manually change it for you. Can you email me using the address that owns the account with the new info you want: leafot@gmail.com

**Comment by supergooddave** [comment]
I just emailed you from the existing account with the new info. Thanks.

**Comment by leafo** [comment]
@supergooddave I don't see the email, what was the subject

**Comment by supergooddave** [comment]
I just resent it, subject was:

Fwd: [leafo/streak.club] Add ability to change email address and username (#46)

**Comment by supergooddave** [comment]
Thanks, I'm all set.  I appreciate you changing my account.
