### ISSUE TITLE
Cannot display personal Website on profile page unless a Twitter handle is included.

### ISSUE THREAD

**Issue by kevinfiol** [leafo/streak.club#53]
Title is somewhat self-explanatory.

Unsure if this is a verification measure or not, but as it stands, it is somewhat frustrating to those users who choose not to use Twitter (I use Mastodon instead, for example).

Screenshots:
![capture](https://user-images.githubusercontent.com/4752973/49112677-6a104200-f261-11e8-9718-0d6c78270b53.PNG)
![capture2](https://user-images.githubusercontent.com/4752973/49112680-6d0b3280-f261-11e8-9ec8-b381ac0d2b70.PNG)

**Comment by kevinfiol** [comment]
Issue seems to lie here. Apologies, I'm not familiar with Lua, MoonScript, or Lapis: https://github.com/leafo/streak.club/blob/master/views/user_profile.moon#L28

**Comment by leafo** [comment]
sorry I didn't get a chance to fix this sooner. You found the spot where the bug was, I made a quick refactor for the fix

**Comment by kevinfiol** [comment]
No worries. Thanks for the fix.
