### ISSUE TITLE
Should streaks require end dates?

### ISSUE THREAD

**Issue by rileyjshaw** [leafo/streak.club#6]
*This is more of a question than an issue.*

Should streaks require end dates? I just started a streak, and plan to continue it indefinitely. It would be nice if I could hit "I'm done now" at some point in the future, with no end in sight until then.

**Comment by leafo** [comment]
It definitely would be nice to have streaks with no date limits. It doesn't map easily to the system I have now, so it would be a more complicated change. I can't say when I'll get a chance to add something like this but I'll keep it in mind.

**Comment by leafo** [comment]
it's been there all this year
