### ISSUE TITLE
Your account under review!

### ISSUE THREAD

**Issue by BGArtist3920** [leafo/streak.club#63]
Your profile is not publicly visible. Please contact an admin to get the issue resolved. This may be due to our automated spam detector.

Does this mean there's something wrong with my account? Is there a way to resolve this?
Sorry I am very new to this, have no idea how all these work :(

**Comment by leafo** [comment]
Hey, sorry for taking a while to get back to you. Can you leave a link to your account there so I can look.

We got hit with a ton of spam accounts, and our spam detector is still being trained so some new accounts may accidentally get flagged for review before they are publicly available. Generally though, for logged in viewers, your account will still function as normal.

**Comment by undefdev** [comment]
Since there's already an issue open for this, [here](https://streak.club/u/undef)'s my account. Thanks for having a look!

**Comment by leafo** [comment]
Sorry about the delay. Your account should be all set now

**Comment by leafo** [comment]
@BGArtist3920 you need to include a link to your account so I can review it
