### ISSUE TITLE
My account was flagged as spam seconds after creation

### ISSUE THREAD

**Issue by Brandon-JYB** [leafo/streak.club#66]
Why am I flagged as spam? I literally just created my account. I haven't even done anything yet.

**Comment by leafo** [comment]
You will need to include a link to your account here so we can review it.

Unfortunately, the site go hit with a large amount of spammers, based on the network activity of previous spammers, your new account may be classified as potentially being risky. Sorry! The more users we get that aren't malicious the more we can train the classifier, but until the your account is not public until approved by an admin.

**Comment by Brandon-JYB** [comment]
I'm really sorry for the late reply, but someone else already fixed my
account. I rarely check my gmail so I only read this today. Very sorry!
