### ISSUE TITLE
sorting submited files

### ISSUE THREAD

**Issue by jpcloud** [leafo/streak.club#8]
I have submitted two gifs - and no matter how I sort them (using "move up" and "move down") the order does not change. 

Link: http://streak.club/submission/764

Can anybody confirm that I am not doing anything wrong?

**Comment by jpcloud** [comment]
This still does not work.
http://streak.club/submission/1625 <- has two gifs, can't change the order.
Wether I try moving the top one down and save, or the lower one up and save, it's always back to it's original state.

(Or isn't the fix simply not on the live system?)

**Comment by leafo** [comment]
Ah you're right, I didn't deploy it. Should be good now. Thanks

**Comment by jpcloud** [comment]
indeed, now it works. thank you :)
